### ISSUE TITLE
Improve logging and debugging documentation

### ISSUE THREAD

**Issue by CMeeg** [CMeeg/gridsome-source-kentico-kontent#5]
This issue was raised in #2:

> I wanted to dig into this more and learn how the plugin was working.
>
> I started with export DEBUG=* to turn on the debug package you're using.
>
> The export DEBUG=* might be helpful to put in the README for devs looking to diagnose issues.

**Comment by CMeeg** [comment]
Hi @seangwright,

Thanks for the suggestion to improve the docs. I just wanted to ask how you had been using the debug library as it looks like you are using it differently to me, and I want to make the docs as useful as possible.

I have been using it on the [command line](https://github.com/visionmedia/debug#windows-command-prompt-notes), for example:

`set DEBUG=gridsome-source-kentico-cloud,gridsome-source-kentico-cloud:source & npm run develop`

I've been looking at the debug docs and couldn't see a mention of using `export` - where and how are you using that?

A bit of context for you - I'm fairly new to writing node modules/npm packages and this is the first time I've used the debug library so I'm still learning!

Cheers

**Comment by seangwright** [comment]
I'm using Gitbash as my shell and ConEmu as my terminal so my syntax is going to be bash based.

`export DEBUG=*` flips on all logging for the `debug` package in bash.

If I were using powershell or cmd I would use `$env:DEBUG="*"` and `set DEBUG=*` respectively.

I haven't made many npm packages myself, though I've been doing a lot of JavaScript for the past 4-5 years.

I definitely appreciate you making this plugin as I prefer VueJs to React so Gridsome seems like a great option for consuming Kentico Cloud.

I wouldn't even be attempting any of this if your plugin didn't already exist!

**Comment by CMeeg** [comment]
Ah I see, thanks @seangwright - I will update the docs with some examples to clarify usage.

No worries - thanks for all your feedback so far and helping me catch a couple of bugs. I just wanted to get some experience with Kentico Cloud, Gridsome and Vue myself so started writing this plugin, and thought it might be something good to share. Now I've released the plugin I might actually finish the site I started to build in the first place!

**Comment by seangwright** [comment]
All your work is very appreciated!

Looks like we're gonna have to start calling it [Kontent instead of Kentico Cloud](https://twitter.com/seangwright/status/1173617868526821377).

I've been using VueJs a lot on a Kentico 12 MVC application, I've done some NuxtJs, and saw you created this plugin for Gridsome and figured it was right up my alley.
