### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by ChristopherJennings** [CMeeg/gridsome-source-kentico-kontent#8]
As @seangwright mentioned in [A comment in #5](https://github.com/CMeeg/gridsome-source-kentico-cloud/issues/5#issuecomment-532020335), We just announced a rebrand of the product. When you get a chance it'd be great if you could update this plugin to reflect that new brand, "Kentico Kontent"

On an unrelated note, I've been working with the plugin in my free time the last couple of weeks converting [the Vue travel blog sample](https://github.com/kentico/cloud-sample-app-vue-blog-travel/) I built and I'm nearly complete. I've run into very few issues that I couldn't resolve quickly and they were all mostly due to my lack of understanding of Gridsome or GraphQL. I've been super pleased with this plugin!

**Comment by CMeeg** [comment]
Thanks for the comments @ChristopherJennings - I'm really pleased the plugin has been working well for you!

I saw the announcement of the rebrand - congrats on that! I will bring the plugin in line with the new brand in the next release, which I am planning to also include #7 and #9.

**Comment by CMeeg** [comment]
Hi @ChristopherJennings - with the rebrand, would it be better to rename the plugin:

* `gridsome-source-kontent`; or
* `gridsome-source-kentico-kontent`

**Comment by petrsvihlik** [comment]
Guidelines: https://gitter.im/Kentico/Kontent?at=5d8b643d692d464f7969c6d9

I'd go for `gridsome-source-kentico-kontent`

**Comment by ChristopherJennings** [comment]
Hi, 
Sorry for the delay in my response. 

We've just published [guidelines for the community here](https://github.com/orgs/Kentico/teams/global-collaborators/discussions/7).

As your plugin is outside of our github organization, naming would be `gridsome-source-kentico-kontent`, since there's an established pattern for Gridsome plugins already, we defer to that.

**Comment by CMeeg** [comment]
Great, thanks @petrsvihlik and @ChristopherJennings :)

I'm pretty much done with changes related to the rebrand and upgrade to the latest js sdk. I'll hopefully get some time in the coming days to finalise and push.
