### ISSUE TITLE
Update SDK version to latest

### ISSUE THREAD

**Issue by ChristopherJennings** [CMeeg/gridsome-source-kentico-kontent#9]
The JS SDK got some major updates in the V6 release which occured right around the time you released this plugin. Additionally, in support of the rebranding mentioned in #8, V7 was released yesterday.

There are a lot of changes in V6 from V5, but the [Upgrade guide](https://github.com/Kentico/kentico-kontent-js/blob/master/packages/delivery/UPGRADE.md) should cover just about all of them. 

Thanks for all your efforts on this plugin!

**Comment by CMeeg** [comment]
I think this will be the main focus of the next release - thanks for the link to the upgrade guide @ChristopherJennings.

Once that is done I will likely look to support the latest version of Gridsome, which also dropped recently.
